// A fixed catalogue of ~72 small-business ideas (8+ per soha) with grounded, conservative
// cost/income ranges (so'm). The business-plan wizard (see src/actions/ai.ts) selects the
// best-fitting entries from this catalogue instead of free-generating numbers — this is
// what keeps its answers "ishonchli va tekshirilgan asosda" (grounded, not hallucinated):
// the actual cost/income figures shown to the user always come from here, never invented.

export type Soha =
  | "Xizmat ko'rsatish"
  | "Savdo"
  | "Oziq-ovqat"
  | "Ishlab chiqarish"
  | "Qishloq xo'jaligi"
  | "Qurilish"
  | "IT va raqamli xizmatlar"
  | "Ta'lim"
  | "Turizm va mehmondo'stlik";

export const SOHALAR: Soha[] = [
  "Xizmat ko'rsatish",
  "Savdo",
  "Oziq-ovqat",
  "Ishlab chiqarish",
  "Qishloq xo'jaligi",
  "Qurilish",
  "IT va raqamli xizmatlar",
  "Ta'lim",
  "Turizm va mehmondo'stlik",
];

export type Tajriba = "Yangi boshlovchi" | "Tajribam bor" | "Ikkalasi";

export type BusinessIdeaTemplate = {
  id: string;
  nomi: string;
  soha: Soha;
  tavsif: string;
  costMin: number;
  costMax: number;
  incomeMin: number;
  incomeMax: number;
  /** Substrings matched (case-insensitively) against a mahalla's `drayver` text to judge
   * local fit — e.g. an idea tagged "xizmat" is boosted for a mahalla whose drayver
   * contains "xizmat ko'rsatish". */
  drayverKalitlari: string[];
  tajriba: Tajriba;
};

export const BUSINESS_IDEAS: BusinessIdeaTemplate[] = [
  // Xizmat ko'rsatish
  {
    id: "sartaroshxona",
    nomi: "Sartaroshxona / go'zallik saloni (mini)",
    soha: "Xizmat ko'rsatish",
    tavsif: "1-2 ustali kichik sartaroshxona yoki go'zallik xizmati shohobchasi.",
    costMin: 8_000_000,
    costMax: 18_000_000,
    incomeMin: 4_000_000,
    incomeMax: 9_000_000,
    drayverKalitlari: ["xizmat"],
    tajriba: "Ikkalasi",
  },
  {
    id: "tikish-tamirlash",
    nomi: "Kiyim tikish va ta'mirlash sexi",
    soha: "Xizmat ko'rsatish",
    tavsif: "Kiyim tikish, o'lchamga moslash va ta'mirlash xizmati ko'rsatuvchi kichik ustaxona.",
    costMin: 5_000_000,
    costMax: 12_000_000,
    incomeMin: 3_000_000,
    incomeMax: 7_000_000,
    drayverKalitlari: ["xizmat"],
    tajriba: "Tajribam bor",
  },
  {
    id: "poyabzal-tamirlash",
    nomi: "Poyabzal ta'mirlash ustaxonasi",
    soha: "Xizmat ko'rsatish",
    tavsif: "Poyabzal va charm buyumlarni ta'mirlash xizmati.",
    costMin: 3_000_000,
    costMax: 7_000_000,
    incomeMin: 2_500_000,
    incomeMax: 5_000_000,
    drayverKalitlari: ["xizmat", "savdo"],
    tajriba: "Yangi boshlovchi",
  },
  {
    id: "avto-yuvish",
    nomi: "Avtomobil yuvish shohobchasi (mini)",
    soha: "Xizmat ko'rsatish",
    tavsif: "Kichik hududda joylashgan qo'lda/yarim avtomatik avtomobil yuvish shohobchasi.",
    costMin: 15_000_000,
    costMax: 35_000_000,
    incomeMin: 6_000_000,
    incomeMax: 14_000_000,
    drayverKalitlari: ["xizmat"],
    tajriba: "Ikkalasi",
  },
  {
    id: "kir-yuvish",
    nomi: "Kir yuvish va dazmollash xizmati",
    soha: "Xizmat ko'rsatish",
    tavsif: "Aholi va kichik korxonalarga kir yuvish-dazmollash xizmati ko'rsatuvchi kombinat.",
    costMin: 10_000_000,
    costMax: 25_000_000,
    incomeMin: 5_000_000,
    incomeMax: 11_000_000,
    drayverKalitlari: ["xizmat"],
    tajriba: "Yangi boshlovchi",
  },
  {
    id: "texnika-tamirlash",
    nomi: "Uy-ro'zg'or texnikasini ta'mirlash ustaxonasi",
    soha: "Xizmat ko'rsatish",
    tavsif: "Muzlatgich, kir yuvish mashinasi va boshqa maishiy texnikani ta'mirlash xizmati.",
    costMin: 6_000_000,
    costMax: 15_000_000,
    incomeMin: 4_000_000,
    incomeMax: 9_000_000,
    drayverKalitlari: ["xizmat"],
    tajriba: "Tajribam bor",
  },
  {
    id: "fotostudiya",
    nomi: "Fotostudiya / tadbirlarni suratga olish xizmati",
    soha: "Xizmat ko'rsatish",
    tavsif: "To'y-marosim va boshqa tadbirlarni suratga/videoga olish xizmati.",
    costMin: 8_000_000,
    costMax: 20_000_000,
    incomeMin: 4_000_000,
    incomeMax: 10_000_000,
    drayverKalitlari: ["xizmat"],
    tajriba: "Ikkalasi",
  },
  {
    id: "uy-tozalash",
    nomi: "Uy va ofislarni tozalash xizmati",
    soha: "Xizmat ko'rsatish",
    tavsif: "Uy va kichik ofislarga muntazam yoki bir martalik tozalash xizmati ko'rsatuvchi brigada.",
    costMin: 4_000_000,
    costMax: 10_000_000,
    incomeMin: 3_000_000,
    incomeMax: 7_000_000,
    drayverKalitlari: ["xizmat"],
    tajriba: "Yangi boshlovchi",
  },

  // Savdo
  {
    id: "mini-market",
    nomi: "Oziq-ovqat mahsulotlari do'koni (mini-market)",
    soha: "Savdo",
    tavsif: "Kundalik ehtiyoj mahsulotlarini sotuvchi kichik mahalla do'koni.",
    costMin: 15_000_000,
    costMax: 40_000_000,
    incomeMin: 6_000_000,
    incomeMax: 15_000_000,
    drayverKalitlari: ["savdo", "oziq-ovqat"],
    tajriba: "Ikkalasi",
  },
  {
    id: "bolalar-kiyim",
    nomi: "Bolalar kiyim-kechak do'koni",
    soha: "Savdo",
    tavsif: "Bolalar kiyimi va aksessuarlari sotiladigan mahalla do'koni.",
    costMin: 10_000_000,
    costMax: 25_000_000,
    incomeMin: 4_000_000,
    incomeMax: 10_000_000,
    drayverKalitlari: ["savdo"],
    tajriba: "Yangi boshlovchi",
  },
  {
    id: "qurilish-materiallari",
    nomi: "Qurilish materiallari do'koni (mayda)",
    soha: "Savdo",
    tavsif: "Mahalliy qurilish-ta'mirlash ehtiyojlari uchun materiallar do'koni.",
    costMin: 20_000_000,
    costMax: 50_000_000,
    incomeMin: 7_000_000,
    incomeMax: 18_000_000,
    drayverKalitlari: ["savdo", "qurilish", "ishlab chiqarish"],
    tajriba: "Tajribam bor",
  },
  {
    id: "xojalik-tovarlari",
    nomi: "Xo'jalik va maishiy tovarlar do'koni",
    soha: "Savdo",
    tavsif: "Uy-ro'zg'or buyumlari va maishiy tovarlar sotiladigan do'kon.",
    costMin: 8_000_000,
    costMax: 20_000_000,
    incomeMin: 4_000_000,
    incomeMax: 9_000_000,
    drayverKalitlari: ["savdo"],
    tajriba: "Yangi boshlovchi",
  },
  {
    id: "onlayn-savdo",
    nomi: "Onlayn savdo (kiyim/aksessuar, marketplace orqali)",
    soha: "Savdo",
    tavsif: "Ijtimoiy tarmoq va marketplace orqali kiyim yoki aksessuar sotish.",
    costMin: 3_000_000,
    costMax: 8_000_000,
    incomeMin: 2_500_000,
    incomeMax: 6_000_000,
    drayverKalitlari: ["savdo"],
    tajriba: "Yangi boshlovchi",
  },
  {
    id: "oyoq-kiyim-dokoni",
    nomi: "Poyabzal / oyoq kiyim do'koni",
    soha: "Savdo",
    tavsif: "Katta-kichiklar uchun poyabzal sotiladigan mahalla do'koni.",
    costMin: 8_000_000,
    costMax: 20_000_000,
    incomeMin: 4_000_000,
    incomeMax: 9_000_000,
    drayverKalitlari: ["savdo"],
    tajriba: "Yangi boshlovchi",
  },
  {
    id: "elektronika-aksessuar",
    nomi: "Telefon va elektronika aksessuarlari do'koni",
    soha: "Savdo",
    tavsif: "Telefon, quloqchin va boshqa elektronika aksessuarlari sotiladigan kichik do'kon.",
    costMin: 10_000_000,
    costMax: 25_000_000,
    incomeMin: 5_000_000,
    incomeMax: 11_000_000,
    drayverKalitlari: ["savdo"],
    tajriba: "Ikkalasi",
  },
  {
    id: "gul-sovgalar-dokoni",
    nomi: "Gul va sovg'alar do'koni",
    soha: "Savdo",
    tavsif: "Bayram va tadbirlar uchun gul kompozitsiyalari va sovg'alar sotiladigan do'kon.",
    costMin: 6_000_000,
    costMax: 15_000_000,
    incomeMin: 3_000_000,
    incomeMax: 7_000_000,
    drayverKalitlari: ["savdo"],
    tajriba: "Yangi boshlovchi",
  },

  // Oziq-ovqat
  {
    id: "nonvoyxona",
    nomi: "Non yopish sexi (mini nonvoyxona)",
    soha: "Oziq-ovqat",
    tavsif: "Kunlik non va non mahsulotlari ishlab chiqaradigan kichik sex.",
    costMin: 10_000_000,
    costMax: 25_000_000,
    incomeMin: 5_000_000,
    incomeMax: 12_000_000,
    drayverKalitlari: ["oziq-ovqat"],
    tajriba: "Tajribam bor",
  },
  {
    id: "milliy-taomlar",
    nomi: "Milliy taomlar tayyorlash va yetkazib berish",
    soha: "Oziq-ovqat",
    tavsif: "Buyurtma asosida uyga/office'ga milliy taom yetkazib berish xizmati.",
    costMin: 6_000_000,
    costMax: 15_000_000,
    incomeMin: 4_000_000,
    incomeMax: 9_000_000,
    drayverKalitlari: ["oziq-ovqat", "xizmat"],
    tajriba: "Ikkalasi",
  },
  {
    id: "konditer",
    nomi: "Konditer sexi (tort va shirinliklar)",
    soha: "Oziq-ovqat",
    tavsif: "Tort, pirojniy va boshqa shirinliklar tayyorlaydigan kichik sex.",
    costMin: 8_000_000,
    costMax: 18_000_000,
    incomeMin: 4_000_000,
    incomeMax: 9_000_000,
    drayverKalitlari: ["oziq-ovqat"],
    tajriba: "Tajribam bor",
  },
  {
    id: "fastfud",
    nomi: "Fastfud / shashlik shohobchasi",
    soha: "Oziq-ovqat",
    tavsif: "Ko'cha bo'yida yoki savdo markazida kichik tez ovqatlanish shohobchasi.",
    costMin: 12_000_000,
    costMax: 28_000_000,
    incomeMin: 6_000_000,
    incomeMax: 13_000_000,
    drayverKalitlari: ["oziq-ovqat"],
    tajriba: "Ikkalasi",
  },
  {
    id: "sut-mahsulotlari",
    nomi: "Sut va sut mahsulotlari sotish nuqtasi",
    soha: "Oziq-ovqat",
    tavsif: "Sut, qatiq, tvorog va boshqa sut mahsulotlarini sotish nuqtasi.",
    costMin: 8_000_000,
    costMax: 18_000_000,
    incomeMin: 4_000_000,
    incomeMax: 9_000_000,
    drayverKalitlari: ["oziq-ovqat", "savdo"],
    tajriba: "Ikkalasi",
  },
  {
    id: "meva-sabzavot-dokoni",
    nomi: "Meva-sabzavot do'koni",
    soha: "Oziq-ovqat",
    tavsif: "Yangi meva va sabzavotlar sotiladigan mahalla do'koni.",
    costMin: 6_000_000,
    costMax: 14_000_000,
    incomeMin: 3_000_000,
    incomeMax: 7_000_000,
    drayverKalitlari: ["oziq-ovqat", "savdo"],
    tajriba: "Yangi boshlovchi",
  },
  {
    id: "muzqaymoq-shirinlik",
    nomi: "Muzqaymoq va salqin ichimliklar shohobchasi",
    soha: "Oziq-ovqat",
    tavsif: "Yoz faslida muzqaymoq va salqin ichimliklar sotadigan mavsumiy shohobcha.",
    costMin: 7_000_000,
    costMax: 16_000_000,
    incomeMin: 4_000_000,
    incomeMax: 9_000_000,
    drayverKalitlari: ["oziq-ovqat"],
    tajriba: "Yangi boshlovchi",
  },
  {
    id: "konservatsiya-marinad",
    nomi: "Konservalash va marinad tayyorlash sexi",
    soha: "Oziq-ovqat",
    tavsif: "Mavsumiy meva-sabzavotlarni konservalash va marinad qilish kichik sexi.",
    costMin: 10_000_000,
    costMax: 22_000_000,
    incomeMin: 5_000_000,
    incomeMax: 11_000_000,
    drayverKalitlari: ["oziq-ovqat", "ishlab chiqarish"],
    tajriba: "Tajribam bor",
  },

  // Ishlab chiqarish
  {
    id: "tikuvchilik-sex",
    nomi: "Tikuvchilik sexi (kichik, 3-5 mashinali)",
    soha: "Ishlab chiqarish",
    tavsif: "Kiyim-kechak seriyali ishlab chiqarish uchun kichik tikuvchilik sexi.",
    costMin: 20_000_000,
    costMax: 45_000_000,
    incomeMin: 8_000_000,
    incomeMax: 18_000_000,
    drayverKalitlari: ["ishlab chiqarish"],
    tajriba: "Tajribam bor",
  },
  {
    id: "mebel-ustaxona",
    nomi: "Mebel yasash ustaxonasi (kichik)",
    soha: "Ishlab chiqarish",
    tavsif: "Buyurtma asosida uy va office mebeli yasaydigan kichik ustaxona.",
    costMin: 25_000_000,
    costMax: 55_000_000,
    incomeMin: 9_000_000,
    incomeMax: 20_000_000,
    drayverKalitlari: ["ishlab chiqarish"],
    tajriba: "Tajribam bor",
  },
  {
    id: "metall-payvand",
    nomi: "Metall va payvandlash ustaxonasi",
    soha: "Ishlab chiqarish",
    tavsif: "Metall konstruksiya, darvoza-panjara va payvandlash xizmatlari ustaxonasi.",
    costMin: 18_000_000,
    costMax: 40_000_000,
    incomeMin: 8_000_000,
    incomeMax: 17_000_000,
    drayverKalitlari: ["ishlab chiqarish"],
    tajriba: "Tajribam bor",
  },
  {
    id: "qadoqlash-sex",
    nomi: "Qadoqlash va etiketka xizmati (kichik korxonalarga)",
    soha: "Ishlab chiqarish",
    tavsif: "Mahalliy ishlab chiqaruvchilarga qadoqlash va markalash xizmati ko'rsatuvchi sex.",
    costMin: 15_000_000,
    costMax: 35_000_000,
    incomeMin: 6_000_000,
    incomeMax: 14_000_000,
    drayverKalitlari: ["ishlab chiqarish", "savdo-sanoat"],
    tajriba: "Ikkalasi",
  },
  {
    id: "gisht-blok-ishlab",
    nomi: "Qurilish bloklari (gishtcha) ishlab chiqarish",
    soha: "Ishlab chiqarish",
    tavsif: "Devor bloklari va bordyur toshlarini ishlab chiqaruvchi kichik sex.",
    costMin: 25_000_000,
    costMax: 60_000_000,
    incomeMin: 10_000_000,
    incomeMax: 22_000_000,
    drayverKalitlari: ["ishlab chiqarish", "qurilish"],
    tajriba: "Tajribam bor",
  },
  {
    id: "plastik-mahsulotlar",
    nomi: "Plastik va PET idishlar ishlab chiqarish sexi",
    soha: "Ishlab chiqarish",
    tavsif: "Plastik idish va qadoqlash materiallari ishlab chiqaruvchi kichik sex.",
    costMin: 30_000_000,
    costMax: 70_000_000,
    incomeMin: 12_000_000,
    incomeMax: 25_000_000,
    drayverKalitlari: ["ishlab chiqarish"],
    tajriba: "Tajribam bor",
  },
  {
    id: "yogoch-ustaxona",
    nomi: "Yog'och ishlash va derazacha-eshik ustaxonasi",
    soha: "Ishlab chiqarish",
    tavsif: "Buyurtma asosida yog'och deraza, eshik va konstruksiya tayyorlaydigan ustaxona.",
    costMin: 20_000_000,
    costMax: 45_000_000,
    incomeMin: 8_000_000,
    incomeMax: 18_000_000,
    drayverKalitlari: ["ishlab chiqarish", "qurilish"],
    tajriba: "Tajribam bor",
  },
  {
    id: "trikotaj-ishlab",
    nomi: "Trikotaj va bosh kiyim ishlab chiqarish mini-sexi",
    soha: "Ishlab chiqarish",
    tavsif: "Trikotaj kiyim va bosh kiyimlarni kichik hajmda ishlab chiqaruvchi sex.",
    costMin: 15_000_000,
    costMax: 35_000_000,
    incomeMin: 6_000_000,
    incomeMax: 14_000_000,
    drayverKalitlari: ["ishlab chiqarish"],
    tajriba: "Ikkalasi",
  },

  // Qishloq xo'jaligi
  {
    id: "issiqxona",
    nomi: "Issiqxonada sabzavot yetishtirish",
    soha: "Qishloq xo'jaligi",
    tavsif: "Yil davomida sabzavot yetishtiradigan kichik issiqxona xo'jaligi.",
    costMin: 15_000_000,
    costMax: 40_000_000,
    incomeMin: 6_000_000,
    incomeMax: 16_000_000,
    drayverKalitlari: ["qishloq", "chorvachilik"],
    tajriba: "Ikkalasi",
  },
  {
    id: "parrandachilik",
    nomi: "Parrandachilik fermasi (tovuq, tuxum)",
    soha: "Qishloq xo'jaligi",
    tavsif: "Tuxum va go'sht uchun kichik parrandachilik fermasi.",
    costMin: 10_000_000,
    costMax: 30_000_000,
    incomeMin: 5_000_000,
    incomeMax: 14_000_000,
    drayverKalitlari: ["qishloq", "chorvachilik"],
    tajriba: "Tajribam bor",
  },
  {
    id: "asalarichilik",
    nomi: "Asalarichilik",
    soha: "Qishloq xo'jaligi",
    tavsif: "Asal va asalarichilik mahsulotlari ishlab chiqarish.",
    costMin: 8_000_000,
    costMax: 20_000_000,
    incomeMin: 3_000_000,
    incomeMax: 9_000_000,
    drayverKalitlari: ["qishloq"],
    tajriba: "Tajribam bor",
  },
  {
    id: "quyonchilik",
    nomi: "Quyonchilik fermasi",
    soha: "Qishloq xo'jaligi",
    tavsif: "Go'sht uchun kichik quyonchilik fermasi.",
    costMin: 6_000_000,
    costMax: 15_000_000,
    incomeMin: 3_000_000,
    incomeMax: 8_000_000,
    drayverKalitlari: ["qishloq", "chorvachilik"],
    tajriba: "Tajribam bor",
  },
  {
    id: "baliqchilik",
    nomi: "Kichik hovuzli baliqchilik xo'jaligi",
    soha: "Qishloq xo'jaligi",
    tavsif: "Sun'iy hovuzda baliq yetishtiruvchi kichik xo'jalik.",
    costMin: 15_000_000,
    costMax: 35_000_000,
    incomeMin: 6_000_000,
    incomeMax: 15_000_000,
    drayverKalitlari: ["qishloq"],
    tajriba: "Tajribam bor",
  },
  {
    id: "kokat-ochiq-maydon",
    nomi: "Ochiq maydonda ko'katlar yetishtirish",
    soha: "Qishloq xo'jaligi",
    tavsif: "Ochiq dalada ko'katlar va tez pishuvchi sabzavotlar yetishtirish.",
    costMin: 5_000_000,
    costMax: 12_000_000,
    incomeMin: 3_000_000,
    incomeMax: 7_000_000,
    drayverKalitlari: ["qishloq"],
    tajriba: "Yangi boshlovchi",
  },
  {
    id: "chorva-boqish",
    nomi: "Mayda shoxli chorva (qo'y-echki) boqish",
    soha: "Qishloq xo'jaligi",
    tavsif: "Go'sht uchun qo'y-echki boqadigan kichik xo'jalik.",
    costMin: 12_000_000,
    costMax: 28_000_000,
    incomeMin: 5_000_000,
    incomeMax: 12_000_000,
    drayverKalitlari: ["qishloq", "chorvachilik"],
    tajriba: "Tajribam bor",
  },
  {
    id: "kochat-pitomnik",
    nomi: "Ko'chat pitomnigi (daraxt/manzarali o'simlik)",
    soha: "Qishloq xo'jaligi",
    tavsif: "Meva daraxti va manzarali o'simlik ko'chatlarini yetishtirib sotish.",
    costMin: 10_000_000,
    costMax: 24_000_000,
    incomeMin: 4_000_000,
    incomeMax: 10_000_000,
    drayverKalitlari: ["qishloq"],
    tajriba: "Ikkalasi",
  },

  // Qurilish
  {
    id: "boyoqchi-brigada",
    nomi: "Ta'mirlash-bo'yoqchilik brigadasi (pudratchi xizmati)",
    soha: "Qurilish",
    tavsif: "Uy va ofis ta'mirlash ishlarini bajaruvchi kichik brigada xizmati.",
    costMin: 5_000_000,
    costMax: 12_000_000,
    incomeMin: 5_000_000,
    incomeMax: 12_000_000,
    drayverKalitlari: ["qurilish", "xizmat"],
    tajriba: "Tajribam bor",
  },
  {
    id: "santexnika-elektrika",
    nomi: "Santexnika va elektrika o'rnatish xizmati",
    soha: "Qurilish",
    tavsif: "Uy va ofislarda santexnika/elektrika montaj va ta'mirlash xizmati.",
    costMin: 6_000_000,
    costMax: 14_000_000,
    incomeMin: 5_000_000,
    incomeMax: 11_000_000,
    drayverKalitlari: ["qurilish", "xizmat"],
    tajriba: "Tajribam bor",
  },
  {
    id: "kafel-terraska",
    nomi: "Kafel-terraska yotqizish xizmati",
    soha: "Qurilish",
    tavsif: "Uy va ofislarda kafel, terraska va laminat yotqizish xizmati.",
    costMin: 5_000_000,
    costMax: 12_000_000,
    incomeMin: 5_000_000,
    incomeMax: 11_000_000,
    drayverKalitlari: ["qurilish", "xizmat"],
    tajriba: "Tajribam bor",
  },
  {
    id: "derazachi-eshikchi",
    nomi: "Plastik deraza-eshik o'rnatish ustaxonasi",
    soha: "Qurilish",
    tavsif: "Plastik va alyuminiy deraza-eshiklarni ishlab chiqarish va o'rnatish xizmati.",
    costMin: 15_000_000,
    costMax: 35_000_000,
    incomeMin: 7_000_000,
    incomeMax: 15_000_000,
    drayverKalitlari: ["qurilish"],
    tajriba: "Tajribam bor",
  },
  {
    id: "qurilish-jihoz-ijara",
    nomi: "Qurilish asbob-uskunalarini ijaraga berish",
    soha: "Qurilish",
    tavsif: "Qurilish-ta'mirlash uchun asbob-uskuna va texnikani ijaraga beruvchi xizmat.",
    costMin: 20_000_000,
    costMax: 45_000_000,
    incomeMin: 6_000_000,
    incomeMax: 13_000_000,
    drayverKalitlari: ["qurilish"],
    tajriba: "Ikkalasi",
  },
  {
    id: "landshaft-dizayn",
    nomi: "Hovli va landshaft dizayni xizmati",
    soha: "Qurilish",
    tavsif: "Hovli, bog' va tashqi hudud dizayni hamda obodonlashtirish xizmati.",
    costMin: 8_000_000,
    costMax: 18_000_000,
    incomeMin: 5_000_000,
    incomeMax: 11_000_000,
    drayverKalitlari: ["qurilish", "xizmat"],
    tajriba: "Tajribam bor",
  },
  {
    id: "tom-yopish",
    nomi: "Tom yopish (shifer/metallcherepitsa) ustaxonasi",
    soha: "Qurilish",
    tavsif: "Uy va inshootlarga tom yopish materiallarini o'rnatish xizmati.",
    costMin: 10_000_000,
    costMax: 22_000_000,
    incomeMin: 6_000_000,
    incomeMax: 13_000_000,
    drayverKalitlari: ["qurilish"],
    tajriba: "Tajribam bor",
  },
  {
    id: "payvand-montaj-brigada",
    nomi: "Payvandlash va metall konstruksiya montaj brigadasi",
    soha: "Qurilish",
    tavsif: "Metall konstruksiya va inshootlarni payvandlab montaj qiluvchi brigada.",
    costMin: 12_000_000,
    costMax: 26_000_000,
    incomeMin: 6_000_000,
    incomeMax: 14_000_000,
    drayverKalitlari: ["qurilish", "ishlab chiqarish"],
    tajriba: "Tajribam bor",
  },

  // IT va raqamli xizmatlar
  {
    id: "smm-sayt",
    nomi: "Kichik biznes uchun sayt/ijtimoiy tarmoq boshqaruvi xizmati",
    soha: "IT va raqamli xizmatlar",
    tavsif: "Mahalliy tadbirkorlarga sayt yaratish va ijtimoiy tarmoq yuritish xizmati.",
    costMin: 3_000_000,
    costMax: 8_000_000,
    incomeMin: 3_000_000,
    incomeMax: 8_000_000,
    drayverKalitlari: ["xizmat"],
    tajriba: "Tajribam bor",
  },
  {
    id: "telefon-tamirlash",
    nomi: "Kompyuter va telefon ta'mirlash xizmati",
    soha: "IT va raqamli xizmatlar",
    tavsif: "Kompyuter, noutbuk va telefonlarni diagnostika qilish va ta'mirlash ustaxonasi.",
    costMin: 5_000_000,
    costMax: 12_000_000,
    incomeMin: 4_000_000,
    incomeMax: 9_000_000,
    drayverKalitlari: ["xizmat"],
    tajriba: "Tajribam bor",
  },
  {
    id: "onlayn-marketing",
    nomi: "Ijtimoiy tarmoq reklama va SMM agentligi (mikro)",
    soha: "IT va raqamli xizmatlar",
    tavsif: "Mahalliy tadbirkorlarga ijtimoiy tarmoqda reklama va kontent yuritish xizmati.",
    costMin: 3_000_000,
    costMax: 8_000_000,
    incomeMin: 3_000_000,
    incomeMax: 8_000_000,
    drayverKalitlari: ["xizmat"],
    tajriba: "Tajribam bor",
  },
  {
    id: "dasturlash-repetitor",
    nomi: "Dasturlash va IT ko'nikmalar bo'yicha repetitorlik",
    soha: "IT va raqamli xizmatlar",
    tavsif: "Onlayn yoki offlayn dasturlash va IT ko'nikmalarini o'rgatish xizmati.",
    costMin: 2_000_000,
    costMax: 6_000_000,
    incomeMin: 3_000_000,
    incomeMax: 7_000_000,
    drayverKalitlari: ["xizmat"],
    tajriba: "Tajribam bor",
  },
  {
    id: "ofis-tex-tamirlash",
    nomi: "Printer va ofis texnikasini ta'mirlash xizmati",
    soha: "IT va raqamli xizmatlar",
    tavsif: "Printer, skaner va boshqa ofis texnikasini diagnostika va ta'mirlash xizmati.",
    costMin: 6_000_000,
    costMax: 14_000_000,
    incomeMin: 4_000_000,
    incomeMax: 9_000_000,
    drayverKalitlari: ["xizmat"],
    tajriba: "Tajribam bor",
  },
  {
    id: "fotoprint-dizayn",
    nomi: "Bannerlar va reklama materiallarini raqamli chop etish",
    soha: "IT va raqamli xizmatlar",
    tavsif: "Banner, vizitka va reklama materiallarini raqamli bosib chiqarish xizmati.",
    costMin: 15_000_000,
    costMax: 35_000_000,
    incomeMin: 6_000_000,
    incomeMax: 14_000_000,
    drayverKalitlari: ["xizmat", "savdo"],
    tajriba: "Tajribam bor",
  },
  {
    id: "internet-klub",
    nomi: "Zamonaviy internet-klub (o'quvchilar uchun)",
    soha: "IT va raqamli xizmatlar",
    tavsif: "O'quvchi-yoshlar uchun kompyuter va internet xizmati ko'rsatuvchi kichik klub.",
    costMin: 20_000_000,
    costMax: 45_000_000,
    incomeMin: 7_000_000,
    incomeMax: 15_000_000,
    drayverKalitlari: ["xizmat"],
    tajriba: "Ikkalasi",
  },
  {
    id: "videokuzatuv-ornatish",
    nomi: "Videokuzatuv va signalizatsiya tizimlarini o'rnatish",
    soha: "IT va raqamli xizmatlar",
    tavsif: "Uy va biznes obyektlariga videokuzatuv hamda signalizatsiya o'rnatish xizmati.",
    costMin: 10_000_000,
    costMax: 22_000_000,
    incomeMin: 6_000_000,
    incomeMax: 13_000_000,
    drayverKalitlari: ["xizmat", "qurilish"],
    tajriba: "Tajribam bor",
  },

  // Ta'lim
  {
    id: "bolalar-bogchasi",
    nomi: "Xususiy bolalar bog'chasi (mini)",
    soha: "Ta'lim",
    tavsif: "Kichik guruh (10-20 bola) uchun mahalla darajasidagi xususiy bolalar bog'chasi.",
    costMin: 25_000_000,
    costMax: 55_000_000,
    incomeMin: 8_000_000,
    incomeMax: 18_000_000,
    drayverKalitlari: ["xizmat"],
    tajriba: "Ikkalasi",
  },
  {
    id: "otqirtish-markazi",
    nomi: "O'quv markazi (til/fan kurslari)",
    soha: "Ta'lim",
    tavsif: "Bolalar va kattalar uchun chet tili yoki fan yo'nalishidagi kichik o'quv markazi.",
    costMin: 8_000_000,
    costMax: 20_000_000,
    incomeMin: 5_000_000,
    incomeMax: 12_000_000,
    drayverKalitlari: ["xizmat"],
    tajriba: "Tajribam bor",
  },
  {
    id: "musiqa-sanat-togarak",
    nomi: "Musiqa va san'at bo'yicha xususiy to'garak",
    soha: "Ta'lim",
    tavsif: "Bolalar uchun musiqa asboblari yoki rasm chizish bo'yicha xususiy to'garak.",
    costMin: 6_000_000,
    costMax: 14_000_000,
    incomeMin: 4_000_000,
    incomeMax: 9_000_000,
    drayverKalitlari: ["xizmat"],
    tajriba: "Tajribam bor",
  },
  {
    id: "sport-seksiya",
    nomi: "Bolalar uchun sport seksiyasi",
    soha: "Ta'lim",
    tavsif: "Kurash, futbol yoki boshqa sport turi bo'yicha bolalar seksiyasi.",
    costMin: 8_000_000,
    costMax: 18_000_000,
    incomeMin: 5_000_000,
    incomeMax: 11_000_000,
    drayverKalitlari: ["xizmat"],
    tajriba: "Tajribam bor",
  },
  {
    id: "avtomaktab-mini",
    nomi: "Haydovchilik guvohnomasi tayyorlov kursi (mini-avtomaktab)",
    soha: "Ta'lim",
    tavsif: "Nazariy va amaliy haydovchilik kurslarini tashkil qiluvchi mini-avtomaktab.",
    costMin: 25_000_000,
    costMax: 55_000_000,
    incomeMin: 8_000_000,
    incomeMax: 18_000_000,
    drayverKalitlari: ["xizmat"],
    tajriba: "Tajribam bor",
  },
  {
    id: "ijodiy-rivojlantiruv",
    nomi: "Bolalar uchun ijodiy rivojlantiruvchi markaz",
    soha: "Ta'lim",
    tavsif: "Mantiqiy fikrlash va ijodkorlikni rivojlantiruvchi mashg'ulotlar markazi.",
    costMin: 10_000_000,
    costMax: 22_000_000,
    incomeMin: 6_000_000,
    incomeMax: 13_000_000,
    drayverKalitlari: ["xizmat"],
    tajriba: "Ikkalasi",
  },
  {
    id: "kasb-hunar-markaz",
    nomi: "Kasb-hunar (sartaroshlik, oshpazlik) o'rgatish markazi",
    soha: "Ta'lim",
    tavsif: "Amaliy kasb-hunar ko'nikmalarini o'rgatuvchi qisqa muddatli kurslar markazi.",
    costMin: 12_000_000,
    costMax: 26_000_000,
    incomeMin: 6_000_000,
    incomeMax: 14_000_000,
    drayverKalitlari: ["xizmat"],
    tajriba: "Tajribam bor",
  },
  {
    id: "chet-tili-filial",
    nomi: "Chet tili (ingliz/rus) markazining filiali",
    soha: "Ta'lim",
    tavsif: "Mahalla darajasida chet tili o'quv markazi filiali.",
    costMin: 9_000_000,
    costMax: 20_000_000,
    incomeMin: 6_000_000,
    incomeMax: 13_000_000,
    drayverKalitlari: ["xizmat"],
    tajriba: "Tajribam bor",
  },

  // Turizm va mehmondo'stlik
  {
    id: "gostinitsa",
    nomi: "Mehmon uyi (kichik gostinitsa)",
    soha: "Turizm va mehmondo'stlik",
    tavsif: "PQ-49 turizm imtiyozlariga mos, kichik hajmdagi mehmon uyi xizmati.",
    costMin: 30_000_000,
    costMax: 80_000_000,
    incomeMin: 8_000_000,
    incomeMax: 20_000_000,
    drayverKalitlari: ["turizm", "xizmat"],
    tajriba: "Tajribam bor",
  },
  {
    id: "milliy-taomlar-kafe",
    nomi: "Milliy taomlar kafesi",
    soha: "Turizm va mehmondo'stlik",
    tavsif: "Mahalliy va milliy taomlarga ixtisoslashgan kichik kafe-restoran.",
    costMin: 25_000_000,
    costMax: 60_000_000,
    incomeMin: 10_000_000,
    incomeMax: 22_000_000,
    drayverKalitlari: ["oziq-ovqat", "xizmat", "turizm"],
    tajriba: "Tajribam bor",
  },
  {
    id: "gid-sayohat-xizmati",
    nomi: "Mahalliy gid va sayohat tashkil etish xizmati",
    soha: "Turizm va mehmondo'stlik",
    tavsif: "Mehmonlar uchun mahalliy diqqatga sazovor joylar bo'yicha gid xizmati.",
    costMin: 4_000_000,
    costMax: 10_000_000,
    incomeMin: 3_000_000,
    incomeMax: 8_000_000,
    drayverKalitlari: ["turizm", "xizmat"],
    tajriba: "Tajribam bor",
  },
  {
    id: "hunarmandchilik-suvenir",
    nomi: "Milliy hunarmandchilik buyumlari (suvenir) do'koni",
    soha: "Turizm va mehmondo'stlik",
    tavsif: "Turistlar uchun milliy hunarmandchilik va suvenir buyumlari sotiladigan do'kon.",
    costMin: 6_000_000,
    costMax: 15_000_000,
    incomeMin: 3_000_000,
    incomeMax: 8_000_000,
    drayverKalitlari: ["turizm", "savdo"],
    tajriba: "Yangi boshlovchi",
  },
  {
    id: "event-tashkilotchilik",
    nomi: "To'y-marosim tashkilotchilik xizmati",
    soha: "Turizm va mehmondo'stlik",
    tavsif: "To'y va marosimlarni to'liq tashkil etuvchi xizmat (dekor, dastur, taomnoma).",
    costMin: 10_000_000,
    costMax: 24_000_000,
    incomeMin: 6_000_000,
    incomeMax: 14_000_000,
    drayverKalitlari: ["turizm", "xizmat"],
    tajriba: "Tajribam bor",
  },
  {
    id: "dam-olish-maskani",
    nomi: "Shahar atrofida kichik dam olish maskani",
    soha: "Turizm va mehmondo'stlik",
    tavsif: "Oilaviy dam olish uchun kichik hajmdagi tabiat qo'ynidagi maskan.",
    costMin: 40_000_000,
    costMax: 90_000_000,
    incomeMin: 12_000_000,
    incomeMax: 26_000_000,
    drayverKalitlari: ["turizm"],
    tajriba: "Tajribam bor",
  },
  {
    id: "avto-ijara-turist",
    nomi: "Avtomobil ijaraga berish xizmati",
    soha: "Turizm va mehmondo'stlik",
    tavsif: "Mehmonlar va turistlar uchun avtomobil ijaraga berish xizmati.",
    costMin: 30_000_000,
    costMax: 70_000_000,
    incomeMin: 10_000_000,
    incomeMax: 20_000_000,
    drayverKalitlari: ["turizm", "xizmat"],
    tajriba: "Tajribam bor",
  },
  {
    id: "transport-transfer",
    nomi: "Yo'lovchi tashish / transfer xizmati",
    soha: "Turizm va mehmondo'stlik",
    tavsif: "Mehmonlarni aeroport/vokzaldan yetkazib qo'yish transfer xizmati.",
    costMin: 15_000_000,
    costMax: 35_000_000,
    incomeMin: 7_000_000,
    incomeMax: 15_000_000,
    drayverKalitlari: ["turizm", "xizmat"],
    tajriba: "Ikkalasi",
  },
];
